name: unittest action

on:
  push:
    branches:
      - main
      - develop

jobs:
  unitTest:
    name: unittest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          run: python --version
      - name: pipenv install
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      - name: run pytest
        run: |
          pipenv shell
          pipenv install --dev
          PATHONPATH="./src" pytest -v tests/
